name: findmap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Custom dependencies
  google_nav_bar: ^5.0.5
  line_icons: ^2.0.1
  badges: ^2.0.1
  http: ^0.13.3
  json_annotation: ^4.0.1
  flutter_secure_storage: ^4.2.0
  flutter_multi_formatter: ^2.3.1
  animations: ^1.1.2
  webview_flutter: ^2.0.10
  async: ^2.6.0
  cupertino_icons: ^1.0.2
  flutter_slidable: ^1.0.0-dev.8
  extended_image: ^4.1.0
  smart_select: ^4.3.2
  pull_to_refresh: ^2.0.0
  flutter_email_sender: ^5.0.2
  device_info: ^2.0.2
  package_info: ^2.0.2
  ios_utsname_ext: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
#  flutter_launcher_icons: ^0.9.0
#  flutter_native_splash: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/archive_basic.png
    - assets/loading.gif
  fonts:
    - family: FugazOne
      fonts:
        - asset: assets/fonts/FugazOne-Regular.ttf
    - family: NanumBarunGothic
      fonts:
        - asset: assets/fonts/NanumBarunGothic.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_with_name.png

  color_dark: "#737373"
  image_dark: assets/logo_with_name.png

  android: true
  ios: true
  #web: false

  fullscreen: true
#  android12: true

flutter_icons:
  andoird: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

